trigger:
  branches:
    include:
    - 'master'
    - 'develop'
    - 'feature/*'     # build all branches
  paths:
    exclude:
    - docs/*  # exclude the docs folder

pool:
  vmImage: 'ubuntu-latest'
  depends:
    - npm

variables:
    buildConfiguration: 'Release'
    clientAppDir: './Galaxy/Galaxy.Web/ClientApp/'
    dotnetSdkVersion: '2.1.x'

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet 2.1.x'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    command: 'install'
    workingDir: '$(clientAppDir)'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'token-kraken'
    organization: 'mmm'
    scannerMode: 'MSBuild'
    projectKey: 'mmm-galaxy'
    projectName: 'Galaxy'
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: succeeded()